[package]
name = "woco_carplan"
version = "0.1.0"
authors = ["fschutt <felix.schuett@maps4print.com>"]
edition = "2018"

[dependencies]
log = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
urlencoding = "*"
web-view = "*"
fern = "*"